#!/bin/bash

redshift -l -30:-70 -t 6500:2500 &
xset r rate 300 50 &
setxkbmap -layout us -variant intl &
unclutter &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
slstatus &
xwallpaper --zoom /home/lucas/Desktop/wall.png &
emacs-27 --daemon &

