#!/bin/bash

redshift -l 55.7:12.6 -t 5700:2600 -b 1.0:0.7 -g 0.9 -m randr -v &
xset r rate 300 50 &
setxkbmap -layout us -variant intl -option ctrl:nocaps,altwin:menu_win &
unclutter &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
slstatus &
xwallpaper --zoom /home/lucas/Descargas/bg.png &
emacs-28 --daemon &

